### ISSUE TITLE
Which repository did you use to train DDPM?

### ISSUE THREAD

**Issue by yiyin-s** [PKU-ML/adainf#3]
Thank you for your wonderful exploration of generated data! In Table 6 of the paper, DDPM takes the shortest time to converge, so I wanna try DDPM because it seemed to be the easiest to follow. Could you please share your code for training DDPM?

**Comment by jizhejz** [comment]
Thanks for your question. In the experiments of our paper on DDPM, we directly utilized this [checkpoint](https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/baseline/baseline-cifar10-32x32-uncond-vp.pkl) to generate data. So we need not  to train a new generative model. Please refer to this [link](https://github.com/NVlabs/edm?tab=readme-ov-file) for instructions on how to use this checkpoint.

**Comment by yiyin-s** [comment]
Thank you!
